### ISSUE TITLE
Training data & eval data

### ISSUE THREAD

**Issue by Jay-IPL** [epic-kitchens/VISOR-VOS#1]
Thanks for sharing this code.

In the paper section H.1 (Table 9) shows Train Seq =5,309, Val Seq=1,244. What does Seq mean?

From table 2, there are 115 videos for training, 43 videos for val.

**Comment by AhmadDarKhalil** [comment]
Thanks for your question,
The number of videos in table 2 indicates the number of untrimmed EPIC-KITCHENS videos used in VISOR. We divided these long and untrimmed videos into shorter subsequences (subsequences called "Seq" in section H.1, table 9). For more information on how we built our subsequences, I suggest reading section 3.1 and Figure 2 in the paper.

**Comment by Jay-IPL** [comment]
thanks for the clarification!

After I downloaded the VISOR dataset. In total there are 115 video folders inside 'GroundTruth-SparseAnnotations/rgb_frames/train'. such as 'P01_01' folder.

And in the annotation json file, I saw there is a 'subsequence' field for each frame, such as "subsequence": "P01_07_seq_00002". I guess this field is **the only identifier** to split untrimmed videos into subsequences, right?

besides, in table 9, what does Obj/Seq mu/sigma, min, max mean? for example 5.2/2.1, 1, 13?

**Comment by AhmadDarKhalil** [comment]
Exactly, the 'subsequence' is used with **all sparse frames** to indicate the subsequence value the frame belongs to (each frame must belong to a subsequence as shown in Figure 2 in the paper). For more information about the fields in the JSON files, please refer to this link: [sparse-annotations-fields](https://github.com/epic-kitchens/VISOR-VIS#ground-truth---sparse-annotations)
For table 9, 
Obj/Seq mu/sigma => the (mean)/(standard deviation) of the number of objects per subsequence. i.e. 5.2/2.1 means the number of objects per subsequence=5.2 with 2.1 standard deviation.
Min, Max => the minimum and the maximum number of objects per subsequence. i.e. 1,13 means Min=1 and Max=13 objects per subsequence
I hope this clarifies your confusion.
