### ISSUE TITLE
How to achieve dense frames？

### ISSUE THREAD

**Issue by xljh0520** [epic-kitchens/VISOR-VOS#4]
I noticed that there are [DenseAnnotations](https://data.bris.ac.uk/data/dataset/a303c84f43214cdb0f31d53f51aa4786) for VISOR. But how could I achieve the dense frames?

**Comment by dimadamen** [comment]
As detailed on our webpage: https://epic-kitchens.github.io/VISOR/#downloads
You need to check the other repos we made available. For frame extraction specifically the repo is: https://github.com/epic-kitchens/VISOR-FrameExtraction

**Comment by xljh0520** [comment]
Thanks for your reply. 
Is it allowed to use the dense frames and annotations to train our VOS model for VISOR-VOS challenge?

**Comment by dimadamen** [comment]
Yes it is.
