### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by z-jiaming** [epic-kitchens/VISOR-VOS#6]
For convenience, could you please provide the dataset after conversion to DAVIS format?
Thank you so much!

**Comment by dimadamen** [comment]
Apologies but this is not something we can do as it doubles our storage needs.
We have provided you with clear scripts to do the conversion should you wish. If you have any questions about how to use these scripts, we are happy to help.

**Comment by z-jiaming** [comment]
I use visor_to_davis.py to convert VISOR.
But when I eval it, I found 'VISOR_2022/Annotations/480p/P02_09_seq_00046' only has two frames (P02_09_frame_0000042133.png and P02_09_frame_0000042193.png) after converted, because the eval tools remove the first and last frame so that this sequence will be None.

I debug visor_to_davis.py, its seems like name of other frames not in object_keys. 
<img width="500" alt="image" src="https://github.com/epic-kitchens/VISOR-VOS/assets/42411674/0cfb7212-e6d4-4e36-9621-f8f3a354b76b">
<img width="473" alt="image" src="https://github.com/epic-kitchens/VISOR-VOS/assets/42411674/3e065587-1dd3-462c-917e-7aab39347446">
