### ISSUE TITLE
Dataset issue in val split

### ISSUE THREAD

**Issue by z-jiaming** [epic-kitchens/VISOR-VOS#8]
We found problems when examining the val split in converted dataset: P02_12_seq_00054 and P07_110_seq_00009.
In both videos, subsequent frames will have objects (colors) present that were not present in the first frame.

![image](https://github.com/epic-kitchens/VISOR-VOS/assets/42411674/5b31e27b-0266-489b-810e-ad776b507766)

![image](https://github.com/epic-kitchens/VISOR-VOS/assets/42411674/4e296472-416a-409c-85d1-7e82d5830f18)

We convert VISOR to DAVIS-like by following these steps:

1. We download original dataset from https://data.bris.ac.uk/data/dataset/2v6cgv1x04ol22qp9rm9x2j6a7
2. Unzip it like
![image](https://github.com/epic-kitchens/VISOR-VOS/assets/42411674/9516f74e-ec49-472a-977a-a414cb8c5743)
3. Use [visor_to_davis.py](https://github.com/epic-kitchens/VISOR-VOS/blob/main/visor_to_davis.py) to convert val split: python visor_to_davis -set val -keep_first_frame_masks_only 1 -visor_jsons_root ../2v6cgv1x04ol22qp9rm9x2j6a7_2/GroundTruth-SparseAnnotations/annotations -images_root ../2v6cgv1x04ol22qp9rm9x2j6a7_2/GroundTruth-SparseAnnotations/rgb_frames_merged -output_directory ../data

We're trying to figure out if there's something wrong with the way we're converting it, or something else.
Thank you very much for your help!!

**Comment by dimadamen** [comment]
This is not a problem. The annotations are kept as is regardless of the semi-supervised VOS task. 
For any mask that does not appear in the first frame, this is not included in the sequence evaluation for VOS. We encourage you to look at the evaluation code we had set here: https://github.com/epic-kitchens/VISOR-VOS for the task. 
You can see that any masks not present in the first frame is not penalised in the evaluation as it cannot be segmented. 
However these are not removed from the visualisation or the ground truth as the dataset itself is used in a number of different challenges.

**Comment by z-jiaming** [comment]
Thank you for your response.

I would like to reconfirm that I just ignore targets that do not appear in the first frame, even if they are existing in the first frame and are just not labeled by the mask.
Then during inference, I only need to read the mask of the first frame, not the subsequent frames to get the new objects as YouTube-VOS does.
